# Generated by Django 4.0 on 2021-12-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruduser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cruduser',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
